title: Vefhönnun - Tölvubraut
email: gjg@tskoli.is
description: Vefhönnun er hluti af námi í tölvunarfræði í Upplýsingatækniskólanum
baseurl: ""
url: "vefgrunnur.github.io"

collections:
  authors:
    output: true

defaults:
- scope:
    path: ""
    type: "authors"
  values:
    layout: "author"

- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
  values:
    layout: "default"

highlighter: rouge